## Numpy array and basics 


In [1]:
import numpy as np # type: ignore

# numpy is mainly used to operate on similar data type.

# creating Array from list

In [ ]:
# we can create an array using list : use .array() fxn give lisst as argument 

arr_1d = np.array([1,2,3,3,5,6,5,6])
print("1D array: " , arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]]) # give a list as argument not two or three lists
print("2D array: " , arr_2d)


1D array:  [1 2 3 3 5 6 5 6]
2D array:  [[1 2 3]
 [4 5 6]]


# list vs Numpy array

In [2]:
# list vs Numpy array :

py_list = [1,2,3]
print("python list multiplication : " , py_list*5)

# element wise multiplication

np_array = np.array([1,2,3])
print("python array multiplication : " , np_array*5)

import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ", time.time()-start)


start = time.time()
py_array = np.arange(1000000)*2 
#The numpy.arange() function is used to create a NumPy array with evenly spaced values within a specified interval. It is similar to Python's built-in range() function but returns a NumPy array instead of a list. 
print("\n Numpy operation time : ", time.time()-start)





python list multiplication :  [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
python array multiplication :  [ 5 10 15]

 List operation time :  0.04965710639953613

 Numpy operation time :  0.003750324249267578


# Creating array from scratch

In [ ]:
# Zeroes : for creating zero array , "zeros((roe,column))"

zeroes = np.zeros((3,4))
print("zeroes array :\n",zeroes)

# Ones : for creating array of ones , us e "ones(())" fxn

ones = np.ones((3,4))
print("ones array :\n",ones)

# Full : for creating arrray of same number or array of constant number use "full((row,clm),num)" method

full = np.full((2,3),12)
print("full array :\n",full)

# random : for creating a matrix of random numbers we use random class.
#        syntax is "random.random((rows,colmns))"
# random values will fluctuate in btwn 0 and 1.

random = np.random.random((3,4))
print("Random array : \n",random)

# sequence : uses for sequence array , "np.sequence(from,to,gap)"

sequence = np.arange(0,20,2)
print("Sequence array : \n",sequence)



zeroes array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array :
 [[12 12 12]
 [12 12 12]]
Random array : 
 [[0.65842825 0.63242539 0.25535251 0.76105276]
 [0.3113791  0.89344101 0.55654236 0.9663644 ]
 [0.15004023 0.0218437  0.49307734 0.51380181]]
Sequence array : 
 [ 0  2  4  6  8 10 12 14 16 18]


# Vector , Matrix , Tensor

In [ ]:
# vector :  A 1D array

vector = np.array([1,2,3,4])
print("Vector :\n" , vector)

# Matrix : A 2D array 

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix :\n" , matrix)

# Tensor : A generalization of scalars, vectors, and matrices.Higher dimensions = 3D, 4D, … tensors or 3D arrays

tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print("Tensor :\n" , tensor)


Vector :
 [1 2 3 4]
Matrix :
 [[1 2 3]
 [4 5 6]]
Tensor :
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Propertirs of Array

In [ ]:
arr = np.array([[1,2,2,3],[4,True,6,6]])

# Shape : it a property not a method , 'arr.shape'

print("Shape of array : \n" , arr.shape)

# Dimension(ndim) : uses to get dimensions , 'arr.ndim'

print("Dimension of array : \n" , arr.ndim)

# Size : to get size of array , 'arr.size' , total number of elements in the array

print("Size of array : \n" , arr.size)

# Datatype : to get datatype of the arry ,' arr.dtype '

print("Datatype of array : \n" , arr.dtype)

Shape of array : 
 (2, 4)
Dimension of array : 
 2
Size of array : 
 8
Datatype of array : 
 int64


## Array Reshaping

In [ ]:
arr = np.arange(12)

print("Original Array : \n" , arr)

# reshape : we can change a array in any mxn array using ," reshape((row,clmn))"  method.

reshaped = arr.reshape((3,4))
print("Reshaped Array : \n" , reshaped)

# flatten : if we want to make a 1D arrray of flatena array use , flatten() method, returns copy of the original

flatened = reshaped.flatten()
print("Flattened Array : \n" , flatened)

# ravel : revel returnes view, instead of copy 

raaveled = reshaped.ravel()
print("Raveled Array : \n" , raaveled)

# Transpose : uses for transpose , using "T" method

transpose = reshaped.T
print("Transpose Array : \n" , transpose)

Original Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
