## Numpy Array Operations

In [1]:
import numpy as np

# Indexing and Slicing

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])

# Basic Slicing 
arr1 = arr[2:7]
print("Basic Slicing :" , arr1)

# With Step Slicing

arr2 = arr[1:8:2]
print("with step Slicing :" , arr2)

# Negative Slicing 

arr2 = arr[-3]
print("with step Slicing :" , arr2)

Basic Slicing : [3 4 5 6 7]
with step Slicing : [2 4 6 8]
with step Slicing : 7


In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Specific element 

print("Specific element :", arr2d[1,2])

# Entire Row and Entire Column 

print("Entire Row :", arr2d[2])

print("Entire Column :", arr2d[:,2])


Specific element : 6
Entire Row : [7 8 9]
Entire Column : [3 6 9]


## Sorting

In [ ]:
unsorted =  np.array([3,1,4,5,6,7,8,9,4,5,4,54,2,4,5])

# Sort method

print("Sorted Array :" , np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]]) 

# column wise sort :
print("Sorted 2d array by column :",np.sort(arr_2d_unsorted , axis=0))

#  row wise sort of 2d array
print("Sorted 2d array by row :",np.sort(arr_2d_unsorted , axis=1))

Sorted Array : [ 1  2  3  4  4  4  4  5  5  5  6  7  8  9 54]
Sorted 2d array by column : [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array by row : [[1 3]
 [1 2]
 [2 3]]


## Filter

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,1,0])

even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers :" , even_numbers)


Even Numbers : [2 4 6 8 0]


# Filter with mask

In [20]:
mask = numbers > 5
print("Numbers greater than 5 :" , numbers[mask])

Numbers greater than 5 : [6 7 8 9]


## Fancy Indexing vs np.where()

In [25]:

indices = [0,2,4]
print(numbers[indices])

# Where clause = same as masking

where_result = np.where(numbers >5)
print(where_result)
print("Np where :" , numbers[where_result])

# condition array 

condition_arr = np.where(numbers>5 , "true", "false")  # if (numbers>5) then "true" else "false"
print(condition_arr)



[1 3 5]
(array([5, 6, 7, 8]),)
Np where : [6 7 8 9]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'false' 'false']


## Adding and Removing data 

In [28]:
# Merge two array :

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
print("Combined :",combined)

concatinated = np.concatenate((arr1,arr2))
print("Concatinated :" , concatinated)


Combined : [5 7 9]
Concatinated : [1 2 3 4 5 6]


## Array Compatibility

In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,7])

print("Compatibility Shape :" , a.shape == b.shape)
print("Compatibility Shape :" , a.shape == c.shape)

Compatibility Shape : True
Compatibility Shape : False


In [33]:
original = np.array([[1,2],[3,4]])
print("Original : ", original)

# Add new row = using vstack() method

new_row = np.array([[5,6]])

with_new_row = np.vstack((original ,new_row))
print("With new Row :" , with_new_row)

# Add Column =  using hstack() method

new_column = np.array([[7],[8]])

with_new_column = np.hstack((original , new_column ))
print("With new Column :" , with_new_column)


Original :  [[1 2]
 [3 4]]
With new Row : [[1 2]
 [3 4]
 [5 6]]
With new Column : [[1 2 7]
 [3 4 8]]


In [35]:
# Delete = using delete method , pases array and index and return array not the deleted element.

arr = np.array([1,2,3,4,5,6])

deleted = np.delete(arr, 2)
print("Array after deletion : " ,deleted)


Array after deletion :  [1 2 4 5 6]
